# Generated by Django 2.1.2 on 2018-11-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillTo',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.Person')),
            ],
            bases=('invoices.person',),
        ),
        migrations.CreateModel(
            name='InvoiceFor',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='invoices.Person')),
            ],
            bases=('invoices.person',),
        ),
        migrations.RemoveField(
            model_name='person',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='work',
            name='invoice',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='invoicefor',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
        migrations.AddField(
            model_name='billto',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.Invoice'),
        ),
    ]
