# Generated by Django 2.1.2 on 2018-11-11 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20181111_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='job_number',
            field=models.CharField(default='Job', max_length=100),
        ),
    ]
