# Generated by Django 2.1.2 on 2018-11-14 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_invoice_job_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billto',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicefor',
            name='invoice',
        ),
        migrations.AddField(
            model_name='invoice',
            name='bill_to',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='invoices.BillTo'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_for',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoiceFor'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(),
        ),
    ]
