# Generated by Django 2.1.2 on 2018-11-14 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_auto_20181114_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='bill_to',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='invoices.BillTo'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_for',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='invoices.InvoiceFor'),
        ),
    ]
