# Generated by Django 2.1.2 on 2018-11-15 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_auto_20181114_0411'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone_number',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
