# Generated by Django 2.2.1 on 2019-05-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_invoice_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid_on',
            field=models.DateField(blank=True, null=True, verbose_name='Paid On'),
        ),
    ]
