# Generated by Django 2.2.1 on 2019-05-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_invoice_paid_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='paid_on',
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Payment Notes'),
        ),
    ]
