# Generated by Django 2.2.1 on 2019-05-17 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_auto_20190517_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='payment_notes',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Payment Notes'),
        ),
    ]
